<?php
/**
 * @file
 * Support retrieving and displaying tweets
 */

/**
* Define our name space and sub-spaces in $_SESSION
*/
define('TWFILTER', 'twfilter_module_session');
define('SEARCH_TERM', 'search_term');

 /**
  * Implements hook_menu().
  */
function twfilter_menu() {
  $items['search_tweets'] = array(
    'title' => 'Search Tweets',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('search_tweets_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['read_tweets'] = array(
    'title' => 'Found Tweets',
    'page callback' => 'read_tweets',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/*
 * Implements hook_form()
 */
function search_tweets_form() {
  $form['search_term'] = array(
    '#title' => 'Twitter Search Term',
    '#type' => 'textfield',
    '#description' => t('Enter Search Term such as words @names, #hashtags etc.'),
    '#required' => TRUE,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Search for Tweets',
  );
  return $form;
}


/**
 * Implements hook_form_submit().
 */
function search_tweets_form_submit($form, &$form_state) {
  $_SESSION[TWFILTER][SEARCH_TERM] = $form_state['values']['search_term'];
  $form_state['redirect'] = 'read_tweets';
}


/**
 * Fetch and Render tweets
 */
function read_tweets() {
  return $_SESSION[TWFILTER][SEARCH_TERM];
}
